# Generated by Django 5.2.7 on 2025-10-30 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_analysis', '0003_interviewquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='user_answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ai_feedback', models.TextField(blank=True, null=True)),
                ('total_questions', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('score', models.FloatField(default=0.0)),
                ('completed', models.BooleanField(default=False)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='cv_analysis.cv')),
            ],
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='interview',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='cv_analysis.interview'),
        ),
        migrations.DeleteModel(
            name='InterviewFeedback',
        ),
    ]
