# Generated by Django 5.2.7 on 2025-11-17 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_analysis', '0006_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
